---
kind: pipeline
type: docker
name: development

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - docker build -f Dockerfile -t joseluisq/cubesql:latest .

- name: test
  image: joseluisq/cubesql:latest
  pull: if-not-exists
  commands:
    - cubesql -h

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
    - develop
    - feature/*
    - bugfix/*
    - hotfix/*
    - release/*


---
kind: pipeline
type: docker
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: joseluisq/drone-docker
  privileged: true
  settings:
    repo: joseluisq/cubesql
    dockerfile: Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    build_args:
      - CUBESQL_VERSION=${DRONE_TAG##v}
    auto_tag: true
    auto_tag_aliases:
      - latest

trigger:
  ref:
    include:
    - refs/tags/v*
    exclude:
    - refs/tags/**rc**
    - refs/tags/**alpha**
    - refs/tags/**beta**
    - refs/tags/**latest**


---
kind: pipeline
type: docker
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci-cd

depends_on:
- development
- production

trigger:
  status:
  - success
  - failure
