version: '3'

services:
  cubesql-server:
    image: joseluisq/cubesql:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - "CUBESQL_PORT=4430"
      - "CUBESQL_DATA=/data"
      - "CUBESQL_SETTINGS=/data/cubesql.settings"
    ports:
      - "4430:4430"
    networks:
       - cubesql-net

networks:
  cubesql-net:
    driver: bridge
